INSERT INTO article (category_id, title, content, price, image) 
VALUES 
(1, 'Montre Connectée SmartWatch 3000', 'Montre connectée avec écran tactile, suivi des activités sportives et notifications intelligentes.', 129.99, 'https://www.montresandco.com/37552-thumbnail_product/montre-connectee-smarty-collection-level-en-silicone-noir.jpg'),
(1, 'Casque Bluetooth STEREO-X', 'Casque sans fil avec réduction de bruit, son haute fidélité et batterie longue durée.', 89.99, 'https://m.media-amazon.com/images/I/615M71a98IL.jpg'),
(1, 'Ordinateur Portable Gaming PowerX', 'Ordinateur portable gaming avec processeur Intel i7, carte graphique RTX 3060 et écran 15,6 pouces.', 1499.99, 'https://static.fnac-static.com/multimedia/Images/FR/MDM/b0/77/5b/22771632/1540-1/tsp20241106035952/PC-portable-Gaming-MSI-Raider-GE68-HX-14VIG-480FR-16-QHD-240-Hz-Intel-Core-i9-14900HX-64-Go-RAM-2-To-D-Nvidia-GeForce-RTX-4090-Noir.jpg'),
(1, 'Smartphone Ultra-X 5G', 'Smartphone haut de gamme avec écran AMOLED de 6,7 pouces, appareil photo 108 MP et processeur Snapdragon 888.', 799.99, 'https://static.fnac-static.com/multimedia/Images/20/72/89/10/17340192-1505-3756-1/tsp20241111032535/Samsung-Galaxy-S21-Ultra-5G-5G-smartphone-double-SIM-RAM-12-Go-Memoire-interne-256-Go-ecran-oeL-6-8-3200-x-1440-pixels-120-Hz-4x-cameras-arriere-12-MP-108-MP-10-MP-10-MP-front-camera-40-MP-argent-fantome.jpg'),
(1, 'Chaise Ergonomique ProComfort', 'Chaise de bureau ergonomique avec soutien lombaire réglable, accoudoirs et base pivotante.', 219.99, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRd-LSGWuMDmZttfpcQjWZD1YFm-D7tT5esWA&s'),
(1, 'Table de Travail Compacte', 'Table de travail moderne en bois massif, design épuré avec rangement intégré pour ordinateur portable et accessoires.', 159.99, 'https://m.media-amazon.com/images/I/71THliDTHYL.jpg'),
(1, 'Kit de Voyage Accessoires', 'Set complet d’accessoires pour le voyage incluant un oreiller cervical, masque de sommeil et chargeur portable.', 39.99, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqHjiE6iBNITBk3bDL7UIcxXK5ZlRvvRU9kQ&s'),
(1, 'Lampe de Bureau LED Lumina', 'Lampe de bureau à LED avec intensité lumineuse réglable et port USB pour charger vos appareils.', 30, 'https://www.silvera.fr/eshop/13078-large_default/cloe-led.jpg');