<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLmbyAfe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLmbyAfe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLmbyAfe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLmbyAfe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLmbyAfe\App_KernelDevDebugContainer([
    'container.build_hash' => 'LmbyAfe',
    'container.build_id' => '26e06fc1',
    'container.build_time' => 1734364688,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLmbyAfe');
